services:
  db:
    image: postgres:latest
    container_name: familyemo-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: postgres
    ports:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: familyemo-app
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "8000:8000"
    depends_on:
      - db
      - migrate

  migrate:
    image: migrate/migrate
    container_name: migrate
    depends_on:
      - db
    entrypoint: ["migrate", "-path", "/migrations", "-database", "postgres://postgres:${DB_PASSWORD}@db:5432/postgres?sslmode=disable", "up"]
    volumes:
      - ./schema:/migrations

volumes:
  pgdata:
